name: llm-mlip-env
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy=1.24.3
  - scipy=1.10.1
  - pandas=2.2.2
  - transformers=4.41.2
  - pytorch=1.12.1
  - sympy=1.12
  - flask=1.24.3
  - pip:
    - highlight-text=0.2
