DROP TABLE IF EXISTS mlip;

CREATE TABLE mlip (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT,
  body TEXT NOT NULL,
  annotation TEXT
);